### PR TITLE
Fixed prefix from rmrk to RMRK and recalculated hex

### PR DESCRIPTION
**Pull request by vikiival**

### CODE REVIEW

**Comment by Swader** [comment]
Why? Prefix is case insensitive and we've been fetching it as such. Fetcher has a `prefixes` flag.

**Comment by yangwao** [comment]
Lmao crashed telegram bot?

**Comment by yangwao** [comment]
@Swader I bet you don't want to have this part case insensitive. 

Either we should establish some prettier which part should be how case sensitive but that will create an additional mess.

Why not have all CAPS everywhere? I guess it will create less confusion and promote integrity/consistency of standard.

**Comment by vikiival** [comment]
Also we want to be aligned with consolidator (`does not start with RMRK`)
```js
if (prefix.toUpperCase() !== PREFIX) {
    throw new Error("Invalid remark - does not start with RMRK");
}
```

**Comment by Swader** [comment]
Ok. Not opposed to this but there's a checklist to go through first because of the up-until-now assumption that case doesn't matter:

- [ ] Check how many RMRKs have been issued with lowercase vs uppercase
- [ ] Check if any tools in Tools care about case (i.e. the functions that output remarks from classes, do they use lowercase or uppoercase)
- [ ] Modify all to match
- [ ] Re-fetch full RMRK set with only uppercase, discarding those without
- [ ] Check if the final set looks fine

**Comment by vikiival** [comment]
Screenshot 2021-03-18 at 12 49 32

**Pull request closed without merging**
